import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { WeatherContextProvider } from './_contexts/WeatherContextProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  weather,
}: {
  children: React.ReactNode;
  weather: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <WeatherContextProvider>
        <body className={`${inter.className} h-screen`}>
          <div>{children}</div>
          <div>{weather}</div>
        </body>
      </WeatherContextProvider>
    </html>
  );
}
